include .env

GOOSE=goose
MIGRATIONS=./db/migration

.PHONY: migrate-up migrate-down migrate-status migrate-create

migrate-up:
	$(GOOSE) -dir $(MIGRATIONS) $(DB_DRIVER) "$(DB_URL)" up

migrate-down:
	$(GOOSE) -dir $(MIGRATIONS) $(DB_DRIVER) "$(DB_URL)" down

migrate-status:
	$(GOOSE) -dir $(MIGRATIONS) $(DB_DRIVER) "$(DB_URL)" status

migrate-create:
	@read -p "Migration name: " name; \
	$(GOOSE) -dir $(MIGRATIONS) create $$name sql