// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_management.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBusinessUserProfile = `-- name: CreateBusinessUserProfile :one
INSERT INTO business_profiles(
        user_id,
        owner_name,
        business_type,
        registration_number
) VALUES (
        $1, $2, $3, $4
         )
RETURNING id, user_id, owner_name, business_type, registration_number, approval_status, created_at, updated_at
`

type CreateBusinessUserProfileParams struct {
	UserID             uuid.UUID
	OwnerName          string
	BusinessType       string
	RegistrationNumber string
}

func (q *Queries) CreateBusinessUserProfile(ctx context.Context, arg CreateBusinessUserProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRowContext(ctx, createBusinessUserProfile,
		arg.UserID,
		arg.OwnerName,
		arg.BusinessType,
		arg.RegistrationNumber,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerName,
		&i.BusinessType,
		&i.RegistrationNumber,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    user_id,
    document_type,
    document_url
) VALUES (
             $1, $2, $3
         )
RETURNING id, user_id, document_type, document_url, verified, created_at, updated_at
`

type CreateDocumentParams struct {
	UserID       uuid.UUID
	DocumentType string
	DocumentUrl  string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.UserID, arg.DocumentType, arg.DocumentUrl)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    display_name,
    email,
    phone,
    password_hash,
    role
) VALUES (
             $1, $2, $3, $4, $5
         )
RETURNING id, display_name, email, phone, password_hash, role, is_verified, is_active, created_at, updated_at
`

type CreateUserParams struct {
	DisplayName  string
	Email        string
	Phone        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVendorProfile = `-- name: CreateVendorProfile :one
INSERT INTO vendor_profiles (
    user_id,
    owner_name,
    address,
    registration_number
) VALUES (
             $1, $2, $3, $4
         )
RETURNING id, user_id, owner_name, address, registration_number, approval_status, is_active, created_at, updated_at
`

type CreateVendorProfileParams struct {
	UserID             uuid.UUID
	OwnerName          string
	Address            string
	RegistrationNumber string
}

func (q *Queries) CreateVendorProfile(ctx context.Context, arg CreateVendorProfileParams) (VendorProfile, error) {
	row := q.db.QueryRowContext(ctx, createVendorProfile,
		arg.UserID,
		arg.OwnerName,
		arg.Address,
		arg.RegistrationNumber,
	)
	var i VendorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerName,
		&i.Address,
		&i.RegistrationNumber,
		&i.ApprovalStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessProfileByUserID = `-- name: GetBusinessProfileByUserID :one
SELECT id, user_id, owner_name, business_type, registration_number, approval_status, created_at, updated_at
FROM business_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetBusinessProfileByUserID(ctx context.Context, userID uuid.UUID) (BusinessProfile, error) {
	row := q.db.QueryRowContext(ctx, getBusinessProfileByUserID, userID)
	var i BusinessProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerName,
		&i.BusinessType,
		&i.RegistrationNumber,
		&i.ApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentsByUserID = `-- name: GetDocumentsByUserID :many
SELECT id, user_id, document_type, document_url, verified, created_at, updated_at
FROM documents
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetDocumentsByUserID(ctx context.Context, userID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentType,
			&i.DocumentUrl,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, display_name, email, phone, password_hash, role, is_verified, is_active, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, email, phone, password_hash, role, is_verified, is_active, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, display_name, email, phone, password_hash, role, is_verified, is_active, created_at, updated_at
FROM users
WHERE phone = $1
LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorProfileByUserID = `-- name: GetVendorProfileByUserID :one
SELECT id, user_id, owner_name, address, registration_number, approval_status, is_active, created_at, updated_at
FROM vendor_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetVendorProfileByUserID(ctx context.Context, userID uuid.UUID) (VendorProfile, error) {
	row := q.db.QueryRowContext(ctx, getVendorProfileByUserID, userID)
	var i VendorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerName,
		&i.Address,
		&i.RegistrationNumber,
		&i.ApprovalStatus,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
