// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    allowed_units,
    description,
    is_active,
    created_at,
    updated_at
) VALUES (
             $1,
             $2,
             $3,
             TRUE,
             NOW(),
             NOW()
         )
RETURNING id, name, description, allowed_units, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	Name         string
	AllowedUnits []PricingUnit
	Description  sql.NullString
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, pq.Array(arg.AllowedUnits), arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		pq.Array(&i.AllowedUnits),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, description, allowed_units, is_active, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		pq.Array(&i.AllowedUnits),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, description, allowed_units, is_active, created_at, updated_at
FROM categories
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			pq.Array(&i.AllowedUnits),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, description, allowed_units, is_active, created_at, updated_at FROM categories ORDER BY name ASC
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			pq.Array(&i.AllowedUnits),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryActiveStatus = `-- name: SetCategoryActiveStatus :exec
UPDATE categories
SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetCategoryActiveStatusParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetCategoryActiveStatus(ctx context.Context, arg SetCategoryActiveStatusParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryActiveStatus, arg.ID, arg.IsActive)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $2,
    allowed_units = $3,
    description=$4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, allowed_units, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID           uuid.UUID
	Name         string
	AllowedUnits []PricingUnit
	Description  sql.NullString
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		pq.Array(arg.AllowedUnits),
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		pq.Array(&i.AllowedUnits),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
