// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCommission = `-- name: CreateCommission :one
INSERT INTO commissions (
    order_id,
    vendor_id,
    order_amount,
    commission_percent,
    commission_amount
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, order_id, vendor_id, order_amount, commission_percent, commission_amount, status, paid_at, created_at
`

type CreateCommissionParams struct {
	OrderID           uuid.UUID
	VendorID          uuid.UUID
	OrderAmount       string
	CommissionPercent string
	CommissionAmount  string
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error) {
	row := q.db.QueryRowContext(ctx, createCommission,
		arg.OrderID,
		arg.VendorID,
		arg.OrderAmount,
		arg.CommissionPercent,
		arg.CommissionAmount,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VendorID,
		&i.OrderAmount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCommissionByOrderID = `-- name: GetCommissionByOrderID :one
SELECT id, order_id, vendor_id, order_amount, commission_percent, commission_amount, status, paid_at, created_at FROM commissions WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetCommissionByOrderID(ctx context.Context, orderID uuid.UUID) (Commission, error) {
	row := q.db.QueryRowContext(ctx, getCommissionByOrderID, orderID)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VendorID,
		&i.OrderAmount,
		&i.CommissionPercent,
		&i.CommissionAmount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCommissionsByVendor = `-- name: ListCommissionsByVendor :many
SELECT id, order_id, vendor_id, order_amount, commission_percent, commission_amount, status, paid_at, created_at FROM commissions
WHERE vendor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommissionsByVendorParams struct {
	VendorID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListCommissionsByVendor(ctx context.Context, arg ListCommissionsByVendorParams) ([]Commission, error) {
	rows, err := q.db.QueryContext(ctx, listCommissionsByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commission
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VendorID,
			&i.OrderAmount,
			&i.CommissionPercent,
			&i.CommissionAmount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommissionsAsPaid = `-- name: MarkCommissionsAsPaid :many
UPDATE commissions
SET status = 'PAID',
    paid_at = now()
WHERE vendor_id = $1 AND status = 'PENDING'
RETURNING id, order_id, vendor_id, order_amount, commission_percent, commission_amount, status, paid_at, created_at
`

func (q *Queries) MarkCommissionsAsPaid(ctx context.Context, vendorID uuid.UUID) ([]Commission, error) {
	rows, err := q.db.QueryContext(ctx, markCommissionsAsPaid, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commission
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VendorID,
			&i.OrderAmount,
			&i.CommissionPercent,
			&i.CommissionAmount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
