// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disputes.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (
    order_id,
    raised_by,
    raised_by_id,
    dispute_type,
    description,
    image_url
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, raised_by, raised_by_id, dispute_type, description, image_url, status, admin_decision, adjustment_amount, created_at, updated_at
`

type CreateDisputeParams struct {
	OrderID     uuid.UUID
	RaisedBy    DisputeRaisedBy
	RaisedByID  uuid.UUID
	DisputeType DisputeType
	Description string
	ImageUrl    sql.NullString
}

// Used by: User / Vendor
func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRowContext(ctx, createDispute,
		arg.OrderID,
		arg.RaisedBy,
		arg.RaisedByID,
		arg.DisputeType,
		arg.Description,
		arg.ImageUrl,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RaisedBy,
		&i.RaisedByID,
		&i.DisputeType,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.AdminDecision,
		&i.AdjustmentAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisputeDetailAdmin = `-- name: GetDisputeDetailAdmin :one
SELECT
    d.id,
    d.order_id,
    d.raised_by,
    d.raised_by_id,
    d.dispute_type,
    d.description,
    d.image_url,
    d.status,
    d.admin_decision,
    d.adjustment_amount,
    d.created_at,
    d.updated_at,
    o.request_id,
    o.offer_id,
    o.order_status,
    o.payment_status,
    o.final_price,
    u.id AS user_id,
    u.display_name AS user_name,
    u.email AS user_email,
    u.phone AS user_phone,
    v.id AS vendor_id,
    v.display_name AS vendor_name,
    v.email AS vendor_email,
    v.phone AS vendor_phone
FROM disputes d
JOIN orders o ON o.id = d.order_id
JOIN users u ON u.id = o.user_id
JOIN users v ON v.id = o.vendor_id
WHERE d.id = $1
`

type GetDisputeDetailAdminRow struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	RaisedBy         DisputeRaisedBy
	RaisedByID       uuid.UUID
	DisputeType      DisputeType
	Description      string
	ImageUrl         sql.NullString
	Status           DisputeStatus
	AdminDecision    sql.NullString
	AdjustmentAmount sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	RequestID        uuid.UUID
	OfferID          uuid.UUID
	OrderStatus      OrderStatus
	PaymentStatus    PaymentStatus
	FinalPrice       string
	UserID           uuid.UUID
	UserName         string
	UserEmail        string
	UserPhone        string
	VendorID         uuid.UUID
	VendorName       string
	VendorEmail      string
	VendorPhone      string
}

// Used by: Admin
func (q *Queries) GetDisputeDetailAdmin(ctx context.Context, id uuid.UUID) (GetDisputeDetailAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getDisputeDetailAdmin, id)
	var i GetDisputeDetailAdminRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RaisedBy,
		&i.RaisedByID,
		&i.DisputeType,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.AdminDecision,
		&i.AdjustmentAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestID,
		&i.OfferID,
		&i.OrderStatus,
		&i.PaymentStatus,
		&i.FinalPrice,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.VendorID,
		&i.VendorName,
		&i.VendorEmail,
		&i.VendorPhone,
	)
	return i, err
}

const getOrderDisputeParty = `-- name: GetOrderDisputeParty :one
SELECT
    id,
    user_id,
    vendor_id,
    order_status
FROM orders
WHERE id = $1
`

type GetOrderDisputePartyRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	VendorID    uuid.UUID
	OrderStatus OrderStatus
}

// Used by: Service validation
func (q *Queries) GetOrderDisputeParty(ctx context.Context, id uuid.UUID) (GetOrderDisputePartyRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderDisputeParty, id)
	var i GetOrderDisputePartyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VendorID,
		&i.OrderStatus,
	)
	return i, err
}

const listDisputesAdmin = `-- name: ListDisputesAdmin :many
SELECT
    d.id,
    d.order_id,
    d.raised_by,
    d.raised_by_id,
    d.dispute_type,
    d.description,
    d.image_url,
    d.status,
    d.admin_decision,
    d.adjustment_amount,
    d.created_at,
    d.updated_at,
    o.order_status,
    o.final_price,
    u.display_name AS user_name,
    v.display_name AS vendor_name
FROM disputes d
JOIN orders o ON o.id = d.order_id
JOIN users u ON u.id = o.user_id
JOIN users v ON v.id = o.vendor_id
WHERE (
    $3::dispute_status IS NULL
        OR d.status = $3::dispute_status
    )
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDisputesAdminParams struct {
	Limit  int32
	Offset int32
	Status NullDisputeStatus
}

type ListDisputesAdminRow struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	RaisedBy         DisputeRaisedBy
	RaisedByID       uuid.UUID
	DisputeType      DisputeType
	Description      string
	ImageUrl         sql.NullString
	Status           DisputeStatus
	AdminDecision    sql.NullString
	AdjustmentAmount sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OrderStatus      OrderStatus
	FinalPrice       string
	UserName         string
	VendorName       string
}

// Used by: Admin
func (q *Queries) ListDisputesAdmin(ctx context.Context, arg ListDisputesAdminParams) ([]ListDisputesAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listDisputesAdmin, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisputesAdminRow
	for rows.Next() {
		var i ListDisputesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.RaisedBy,
			&i.RaisedByID,
			&i.DisputeType,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.AdminDecision,
			&i.AdjustmentAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderStatus,
			&i.FinalPrice,
			&i.UserName,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyDisputes = `-- name: ListMyDisputes :many
SELECT
    d.id,
    d.order_id,
    d.raised_by,
    d.raised_by_id,
    d.dispute_type,
    d.description,
    d.image_url,
    d.status,
    d.admin_decision,
    d.adjustment_amount,
    d.created_at,
    d.updated_at,
    o.order_status
FROM disputes d
JOIN orders o ON o.id = d.order_id
WHERE d.raised_by = $1
  AND d.raised_by_id = $2
ORDER BY d.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMyDisputesParams struct {
	RaisedBy   DisputeRaisedBy
	RaisedByID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListMyDisputesRow struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	RaisedBy         DisputeRaisedBy
	RaisedByID       uuid.UUID
	DisputeType      DisputeType
	Description      string
	ImageUrl         sql.NullString
	Status           DisputeStatus
	AdminDecision    sql.NullString
	AdjustmentAmount sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OrderStatus      OrderStatus
}

// Used by: User / Vendor
func (q *Queries) ListMyDisputes(ctx context.Context, arg ListMyDisputesParams) ([]ListMyDisputesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyDisputes,
		arg.RaisedBy,
		arg.RaisedByID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyDisputesRow
	for rows.Next() {
		var i ListMyDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.RaisedBy,
			&i.RaisedByID,
			&i.DisputeType,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.AdminDecision,
			&i.AdjustmentAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE disputes
SET status = $2,
    admin_decision = $3,
    adjustment_amount = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, raised_by, raised_by_id, dispute_type, description, image_url, status, admin_decision, adjustment_amount, created_at, updated_at
`

type ResolveDisputeParams struct {
	ID               uuid.UUID
	Status           DisputeStatus
	AdminDecision    sql.NullString
	AdjustmentAmount sql.NullString
}

// Used by: Admin
func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRowContext(ctx, resolveDispute,
		arg.ID,
		arg.Status,
		arg.AdminDecision,
		arg.AdjustmentAmount,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RaisedBy,
		&i.RaisedByID,
		&i.DisputeType,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.AdminDecision,
		&i.AdjustmentAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
