// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance_stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAdminFinanceStats = `-- name: GetAdminFinanceStats :one
SELECT 
    COALESCE(SUM(c.order_amount), 0)::numeric AS total_completed_order_value,
    COUNT(c.id)::int AS total_completed_orders,
    COALESCE(SUM(c.commission_amount) FILTER (WHERE c.status = 'PAID'), 0)::numeric AS total_platform_earnings,
    COALESCE(SUM(c.commission_amount) FILTER (WHERE c.status = 'PENDING'), 0)::numeric AS total_pending_dues
FROM commissions c
`

type GetAdminFinanceStatsRow struct {
	TotalCompletedOrderValue string
	TotalCompletedOrders     int32
	TotalPlatformEarnings    string
	TotalPendingDues         string
}

func (q *Queries) GetAdminFinanceStats(ctx context.Context) (GetAdminFinanceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminFinanceStats)
	var i GetAdminFinanceStatsRow
	err := row.Scan(
		&i.TotalCompletedOrderValue,
		&i.TotalCompletedOrders,
		&i.TotalPlatformEarnings,
		&i.TotalPendingDues,
	)
	return i, err
}

const getVendorFinanceStats = `-- name: GetVendorFinanceStats :one
SELECT 
    COALESCE(SUM(c.order_amount), 0)::numeric AS total_order_value,
    COUNT(c.id)::int AS total_completed_orders,
    COALESCE(SUM(c.commission_amount), 0)::numeric AS total_commission,
    COALESCE(SUM(c.commission_amount) FILTER (WHERE c.status = 'PAID'), 0)::numeric AS total_paid_to_platform,
    COALESCE(SUM(c.commission_amount) FILTER (WHERE c.status = 'PENDING'), 0)::numeric AS total_pending_due
FROM commissions c
WHERE c.vendor_id = $1
`

type GetVendorFinanceStatsRow struct {
	TotalOrderValue      string
	TotalCompletedOrders int32
	TotalCommission      string
	TotalPaidToPlatform  string
	TotalPendingDue      string
}

func (q *Queries) GetVendorFinanceStats(ctx context.Context, vendorID uuid.UUID) (GetVendorFinanceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getVendorFinanceStats, vendorID)
	var i GetVendorFinanceStatsRow
	err := row.Scan(
		&i.TotalOrderValue,
		&i.TotalCompletedOrders,
		&i.TotalCommission,
		&i.TotalPaidToPlatform,
		&i.TotalPendingDue,
	)
	return i, err
}
