// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DisputeRaisedBy string

const (
	DisputeRaisedByUSER   DisputeRaisedBy = "USER"
	DisputeRaisedByVENDOR DisputeRaisedBy = "VENDOR"
)

func (e *DisputeRaisedBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeRaisedBy(s)
	case string:
		*e = DisputeRaisedBy(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeRaisedBy: %T", src)
	}
	return nil
}

type NullDisputeRaisedBy struct {
	DisputeRaisedBy DisputeRaisedBy
	Valid           bool // Valid is true if DisputeRaisedBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeRaisedBy) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeRaisedBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeRaisedBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeRaisedBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeRaisedBy), nil
}

type DisputeStatus string

const (
	DisputeStatusOPEN        DisputeStatus = "OPEN"
	DisputeStatusUNDERREVIEW DisputeStatus = "UNDER_REVIEW"
	DisputeStatusRESOLVED    DisputeStatus = "RESOLVED"
	DisputeStatusREJECTED    DisputeStatus = "REJECTED"
)

func (e *DisputeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeStatus(s)
	case string:
		*e = DisputeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeStatus: %T", src)
	}
	return nil
}

type NullDisputeStatus struct {
	DisputeStatus DisputeStatus
	Valid         bool // Valid is true if DisputeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeStatus), nil
}

type DisputeType string

const (
	DisputeTypeQuantity DisputeType = "quantity"
	DisputeTypeDamage   DisputeType = "damage"
	DisputeTypeMissing  DisputeType = "missing"
	DisputeTypePricing  DisputeType = "pricing"
)

func (e *DisputeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeType(s)
	case string:
		*e = DisputeType(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeType: %T", src)
	}
	return nil
}

type NullDisputeType struct {
	DisputeType DisputeType
	Valid       bool // Valid is true if DisputeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeType) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeType), nil
}

type OfferStatus string

const (
	OfferStatusPENDING   OfferStatus = "PENDING"
	OfferStatusACCEPTED  OfferStatus = "ACCEPTED"
	OfferStatusREJECTED  OfferStatus = "REJECTED"
	OfferStatusEXPIRED   OfferStatus = "EXPIRED"
	OfferStatusWITHDRAWN OfferStatus = "WITHDRAWN"
)

func (e *OfferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfferStatus(s)
	case string:
		*e = OfferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfferStatus: %T", src)
	}
	return nil
}

type NullOfferStatus struct {
	OfferStatus OfferStatus
	Valid       bool // Valid is true if OfferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfferStatus), nil
}

type OrderStatus string

const (
	OrderStatusACCEPTED   OrderStatus = "ACCEPTED"
	OrderStatusPICKEDUP   OrderStatus = "PICKED_UP"
	OrderStatusINPROGRESS OrderStatus = "IN_PROGRESS"
	OrderStatusDELIVERING OrderStatus = "DELIVERING"
	OrderStatusCOMPLETED  OrderStatus = "COMPLETED"
	OrderStatusCANCELLED  OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCASH   PaymentMethod = "CASH"
	PaymentMethodONLINE PaymentMethod = "ONLINE"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusUNPAID   PaymentStatus = "UNPAID"
	PaymentStatusPAID     PaymentStatus = "PAID"
	PaymentStatusREFUNDED PaymentStatus = "REFUNDED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PricingUnit string

const (
	PricingUnitKG    PricingUnit = "KG"
	PricingUnitSQFT  PricingUnit = "SQFT"
	PricingUnitITEMS PricingUnit = "ITEMS"
)

func (e *PricingUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingUnit(s)
	case string:
		*e = PricingUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingUnit: %T", src)
	}
	return nil
}

type NullPricingUnit struct {
	PricingUnit PricingUnit
	Valid       bool // Valid is true if PricingUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PricingUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingUnit), nil
}

type RequestsStatus string

const (
	RequestsStatusOPEN         RequestsStatus = "OPEN"
	RequestsStatusONBID        RequestsStatus = "ON_BID"
	RequestsStatusEXPIRED      RequestsStatus = "EXPIRED"
	RequestsStatusCANCELLED    RequestsStatus = "CANCELLED"
	RequestsStatusORDERCREATED RequestsStatus = "ORDER_CREATED"
)

func (e *RequestsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestsStatus(s)
	case string:
		*e = RequestsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestsStatus: %T", src)
	}
	return nil
}

type NullRequestsStatus struct {
	RequestsStatus RequestsStatus
	Valid          bool // Valid is true if RequestsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestsStatus), nil
}

type AuthOtpCode struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Email      string
	Purpose    string
	CodeHash   string
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BusinessProfile struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	OwnerName          string
	BusinessType       string
	RegistrationNumber string
	ApprovalStatus     string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Category struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	AllowedUnits []PricingUnit
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Dispute struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	RaisedBy         DisputeRaisedBy
	RaisedByID       uuid.UUID
	DisputeType      DisputeType
	Description      string
	ImageUrl         sql.NullString
	Status           DisputeStatus
	AdminDecision    sql.NullString
	AdjustmentAmount sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Document struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	DocumentType string
	DocumentUrl  string
	Verified     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Notification struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Title       string
	Body        string
	EntityType  sql.NullString
	EntityID    uuid.NullUUID
	ActorUserID uuid.NullUUID
	Data        []byte
	IsRead      bool
	ReadAt      sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Offer struct {
	ID             uuid.UUID
	RequestID      uuid.UUID
	VendorID       uuid.UUID
	BidPrice       string
	CompletionTime time.Time
	ServiceOptions pqtype.NullRawMessage
	Description    sql.NullString
	Status         OfferStatus
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Order struct {
	ID            uuid.UUID
	RequestID     uuid.UUID
	OfferID       uuid.UUID
	UserID        uuid.UUID
	VendorID      uuid.UUID
	FinalPrice    string
	OrderStatus   OrderStatus
	PaymentStatus PaymentStatus
	PickupTime    sql.NullTime
	DeliveryTime  sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PushDeviceToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Platform   string
	Token      string
	DeviceID   sql.NullString
	IsActive   bool
	LastSeenAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Rating struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	UserID    uuid.UUID
	VendorID  uuid.UUID
	Rating    int16
	Review    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Request struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PickupAddress  string
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	PaymentMethod  PaymentMethod
	Status         RequestsStatus
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PickupLat      sql.NullFloat64
	PickupLng      sql.NullFloat64
}

type RequestService struct {
	ID            uuid.UUID
	RequestID     uuid.UUID
	CategoryID    uuid.UUID
	SelectedUnit  PricingUnit
	QuantityValue float64
	ItemsJson     pqtype.NullRawMessage
	Description   sql.NullString
	CreatedAt     time.Time
}

type User struct {
	ID              uuid.UUID
	DisplayName     string
	Email           string
	Phone           string
	PasswordHash    string
	Role            string
	IsVerified      bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ProfileImageUrl sql.NullString
}

type VendorProfile struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	OwnerName          string
	Address            string
	RegistrationNumber string
	ApprovalStatus     string
	IsActive           bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
