// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: offers.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const acceptOffer = `-- name: AcceptOffer :execrows
UPDATE offers
SET status = 'ACCEPTED',
    updated_at = now()
WHERE id = $1
  AND status = 'PENDING'
`

// Used inside: Offer Acceptance Transaction (Concurrency Safe)
func (q *Queries) AcceptOffer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptOffer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (
    request_id,
    vendor_id,
    bid_price,
    completion_time,
    service_options,
    description
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, request_id, vendor_id, bid_price, completion_time, service_options, description, status, created_at, updated_at
`

type CreateOfferParams struct {
	RequestID      uuid.UUID
	VendorID       uuid.UUID
	BidPrice       string
	CompletionTime time.Time
	ServiceOptions pqtype.NullRawMessage
	Description    sql.NullString
}

// Used by: Vendor (Submit Bid)
func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer,
		arg.RequestID,
		arg.VendorID,
		arg.BidPrice,
		arg.CompletionTime,
		arg.ServiceOptions,
		arg.Description,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorID,
		&i.BidPrice,
		&i.CompletionTime,
		&i.ServiceOptions,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOffers = `-- name: ExpireOffers :exec
UPDATE offers
SET status = 'EXPIRED',
    updated_at = now()
WHERE status = 'PENDING'
`

// Not exposed as public API (Background Expiry Job)
func (q *Queries) ExpireOffers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireOffers)
	return err
}

const getOfferStats = `-- name: GetOfferStats :one
SELECT
    COUNT(*) AS total_offers,
    COUNT(*) FILTER (WHERE status = 'PENDING') AS pending_offers,
    COUNT(*) FILTER (WHERE status = 'ACCEPTED') AS accepted_offers,
    COUNT(*) FILTER (WHERE status = 'REJECTED') AS rejected_offers,
    COUNT(*) FILTER (WHERE status = 'EXPIRED') AS expired_offers
FROM offers
`

type GetOfferStatsRow struct {
	TotalOffers    int64
	PendingOffers  int64
	AcceptedOffers int64
	RejectedOffers int64
	ExpiredOffers  int64
}

// Used by: Admin Dashboard
func (q *Queries) GetOfferStats(ctx context.Context) (GetOfferStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getOfferStats)
	var i GetOfferStatsRow
	err := row.Scan(
		&i.TotalOffers,
		&i.PendingOffers,
		&i.AcceptedOffers,
		&i.RejectedOffers,
		&i.ExpiredOffers,
	)
	return i, err
}

const listOffersAdmin = `-- name: ListOffersAdmin :many
SELECT id, request_id, vendor_id, bid_price, completion_time, service_options, description, status, created_at, updated_at
FROM offers
WHERE ($1::offer_status IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR vendor_id = $2)
  AND ($3::uuid IS NULL OR request_id = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListOffersAdminParams struct {
	Column1 OfferStatus
	Column2 uuid.UUID
	Column3 uuid.UUID
	Limit   int32
	Offset  int32
}

// Used by: Admin Panel (Global Offer Listing with Filters)
func (q *Queries) ListOffersAdmin(ctx context.Context, arg ListOffersAdminParams) ([]Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffersAdmin,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.VendorID,
			&i.BidPrice,
			&i.CompletionTime,
			&i.ServiceOptions,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersByRequest = `-- name: ListOffersByRequest :many
SELECT id, request_id, vendor_id, bid_price, completion_time, service_options, description, status, created_at, updated_at
FROM offers
WHERE request_id = $1
ORDER BY created_at DESC
`

// Used by: User (View offers on my request) / Admin
func (q *Queries) ListOffersByRequest(ctx context.Context, requestID uuid.UUID) ([]Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffersByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.VendorID,
			&i.BidPrice,
			&i.CompletionTime,
			&i.ServiceOptions,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersByVendor = `-- name: ListOffersByVendor :many
SELECT id, request_id, vendor_id, bid_price, completion_time, service_options, description, status, created_at, updated_at
FROM offers
WHERE vendor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOffersByVendorParams struct {
	VendorID uuid.UUID
	Limit    int32
	Offset   int32
}

// Used by: Vendor Dashboard
func (q *Queries) ListOffersByVendor(ctx context.Context, arg ListOffersByVendorParams) ([]Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffersByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.VendorID,
			&i.BidPrice,
			&i.CompletionTime,
			&i.ServiceOptions,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOtherOffers = `-- name: RejectOtherOffers :exec
UPDATE offers
SET status = 'REJECTED',
    updated_at = now()
WHERE request_id = $1
  AND id <> $2
  AND status = 'PENDING'
`

type RejectOtherOffersParams struct {
	RequestID uuid.UUID
	ID        uuid.UUID
}

// Used inside: Offer Acceptance Transaction (Reject Others)
func (q *Queries) RejectOtherOffers(ctx context.Context, arg RejectOtherOffersParams) error {
	_, err := q.db.ExecContext(ctx, rejectOtherOffers, arg.RequestID, arg.ID)
	return err
}

const updateOffer = `-- name: UpdateOffer :one
UPDATE offers
SET bid_price = $2,
    completion_time = $3,
    service_options = $4,
    description = $5,
    updated_at = now()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, request_id, vendor_id, bid_price, completion_time, service_options, description, status, created_at, updated_at
`

type UpdateOfferParams struct {
	ID             uuid.UUID
	BidPrice       string
	CompletionTime time.Time
	ServiceOptions pqtype.NullRawMessage
	Description    sql.NullString
}

// Used by: Vendor (Edit Bid while PENDING)
func (q *Queries) UpdateOffer(ctx context.Context, arg UpdateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, updateOffer,
		arg.ID,
		arg.BidPrice,
		arg.CompletionTime,
		arg.ServiceOptions,
		arg.Description,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorID,
		&i.BidPrice,
		&i.CompletionTime,
		&i.ServiceOptions,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawOffer = `-- name: WithdrawOffer :exec
UPDATE offers
SET status = 'REJECTED',
    updated_at = now()
WHERE id = $1
  AND status = 'PENDING'
`

// Used by: Vendor (Withdraw Bid)
func (q *Queries) WithdrawOffer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, withdrawOffer, id)
	return err
}
