// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET order_status = 'CANCELLED',
    updated_at = now()
WHERE id = $1
  AND order_status = 'ACCEPTED'
`

// Used by: User (Cancel Before Pickup)
func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, id)
	return err
}

const completeOrder = `-- name: CompleteOrder :exec
UPDATE orders
SET order_status = 'COMPLETED',
    delivery_time = now(),
    updated_at = now()
WHERE id = $1
  AND order_status = 'DELIVERING'
`

// Used by: Vendor (Mark Completed)
func (q *Queries) CompleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    request_id,
    offer_id,
    user_id,
    vendor_id,
    final_price,
    pickup_time
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, request_id, offer_id, user_id, vendor_id, final_price, order_status, payment_status, pickup_time, delivery_time, created_at, updated_at
`

type CreateOrderParams struct {
	RequestID  uuid.UUID
	OfferID    uuid.UUID
	UserID     uuid.UUID
	VendorID   uuid.UUID
	FinalPrice string
	PickupTime sql.NullTime
}

// Used inside: Offer Acceptance Transaction (Create Order Snapshot)
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.RequestID,
		arg.OfferID,
		arg.UserID,
		arg.VendorID,
		arg.FinalPrice,
		arg.PickupTime,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OfferID,
		&i.UserID,
		&i.VendorID,
		&i.FinalPrice,
		&i.OrderStatus,
		&i.PaymentStatus,
		&i.PickupTime,
		&i.DeliveryTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderDetail = `-- name: GetOrderDetail :one
SELECT
    o.id,
    o.request_id,
    o.final_price,
    o.order_status,
    o.payment_status,
    o.pickup_time,
    o.delivery_time,
    o.created_at,

    u.id AS user_id,
    u.display_name AS user_name,
    u.email AS user_email,
    u.phone AS user_phone,

    v.id AS vendor_id,
    v.display_name AS vendor_name,
    v.email AS vendor_email,
    v.phone AS vendor_phone,

    r.pickup_address,
    r.pickup_time_from,
    r.pickup_time_to,
    r.payment_method,

    COALESCE(s.services_json, '[]'::jsonb) AS services_json

FROM orders o

         JOIN users u ON u.id = o.user_id
         JOIN users v ON v.id = o.vendor_id
         JOIN requests r ON r.id = o.request_id

         LEFT JOIN LATERAL (
    SELECT jsonb_agg(
                   jsonb_build_object(
                           'category_id', c.id,
                           'category_name', c.name,
                           'selected_unit', rs.selected_unit,
                           'quantity_value', rs.quantity_value,
                           'items_json', rs.items_json,
                           'description', rs.description
                   )
           ) AS services_json
    FROM request_services rs
             JOIN categories c ON c.id = rs.category_id
    WHERE rs.request_id = o.request_id
    ) s ON true

WHERE o.id = $1
`

type GetOrderDetailRow struct {
	ID             uuid.UUID
	RequestID      uuid.UUID
	FinalPrice     string
	OrderStatus    OrderStatus
	PaymentStatus  PaymentStatus
	PickupTime     sql.NullTime
	DeliveryTime   sql.NullTime
	CreatedAt      time.Time
	UserID         uuid.UUID
	UserName       string
	UserEmail      string
	UserPhone      string
	VendorID       uuid.UUID
	VendorName     string
	VendorEmail    string
	VendorPhone    string
	PickupAddress  string
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	PaymentMethod  PaymentMethod
	ServicesJson   []byte
}

// Used by: User (My Orders)
func (q *Queries) GetOrderDetail(ctx context.Context, id uuid.UUID) (GetOrderDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderDetail, id)
	var i GetOrderDetailRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.FinalPrice,
		&i.OrderStatus,
		&i.PaymentStatus,
		&i.PickupTime,
		&i.DeliveryTime,
		&i.CreatedAt,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.VendorID,
		&i.VendorName,
		&i.VendorEmail,
		&i.VendorPhone,
		&i.PickupAddress,
		&i.PickupTimeFrom,
		&i.PickupTimeTo,
		&i.PaymentMethod,
		&i.ServicesJson,
	)
	return i, err
}

const getOrderStatsFiltered = `-- name: GetOrderStatsFiltered :one
SELECT
    COUNT(*) AS total_orders,

    COUNT(*) FILTER (WHERE order_status = 'ACCEPTED')    AS accepted_orders,
    COUNT(*) FILTER (WHERE order_status = 'PICKED_UP')   AS picked_up_orders,
    COUNT(*) FILTER (WHERE order_status = 'IN_PROGRESS') AS in_progress_orders,
    COUNT(*) FILTER (WHERE order_status = 'DELIVERING')  AS delivering_orders,
    COUNT(*) FILTER (WHERE order_status = 'COMPLETED')   AS completed_orders,
    COUNT(*) FILTER (WHERE order_status = 'CANCELLED')   AS cancelled_orders

FROM orders
WHERE
    (
        $1::uuid IS NULL
            OR user_id = $1::uuid
        )
  AND
    (
        $2::uuid IS NULL
            OR vendor_id = $2::uuid
        )
`

type GetOrderStatsFilteredParams struct {
	UserID   uuid.NullUUID
	VendorID uuid.NullUUID
}

type GetOrderStatsFilteredRow struct {
	TotalOrders      int64
	AcceptedOrders   int64
	PickedUpOrders   int64
	InProgressOrders int64
	DeliveringOrders int64
	CompletedOrders  int64
	CancelledOrders  int64
}

// Used by: Admin Dashboard (Order Stats)
func (q *Queries) GetOrderStatsFiltered(ctx context.Context, arg GetOrderStatsFilteredParams) (GetOrderStatsFilteredRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderStatsFiltered, arg.UserID, arg.VendorID)
	var i GetOrderStatsFilteredRow
	err := row.Scan(
		&i.TotalOrders,
		&i.AcceptedOrders,
		&i.PickedUpOrders,
		&i.InProgressOrders,
		&i.DeliveringOrders,
		&i.CompletedOrders,
		&i.CancelledOrders,
	)
	return i, err
}

const listOrdersAdmin = `-- name: ListOrdersAdmin :many
SELECT
    o.id,
    o.final_price,
    o.order_status,
    o.payment_status,
    o.created_at,

    u.display_name AS user_name,
    v.display_name AS vendor_name,

    r.pickup_address,

    COALESCE(s.services_json, '[]'::jsonb) AS services_json

FROM orders o

         JOIN users u ON u.id = o.user_id
         JOIN users v ON v.id = o.vendor_id
         JOIN requests r ON r.id = o.request_id

         LEFT JOIN LATERAL (
    SELECT jsonb_agg(
                   jsonb_build_object(
                           'category_id', c.id,
                           'category_name', c.name,
                           'selected_unit', rs.selected_unit,
                           'quantity_value', rs.quantity_value
                   )
           ) AS services_json
    FROM request_services rs
             JOIN categories c ON c.id = rs.category_id
    WHERE rs.request_id = o.request_id
    ) s ON true

WHERE (
          $3::order_status IS NULL
              OR o.order_status = $3::order_status
          )

ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersAdminParams struct {
	Limit  int32
	Offset int32
	Status NullOrderStatus
}

type ListOrdersAdminRow struct {
	ID            uuid.UUID
	FinalPrice    string
	OrderStatus   OrderStatus
	PaymentStatus PaymentStatus
	CreatedAt     time.Time
	UserName      string
	VendorName    string
	PickupAddress string
	ServicesJson  []byte
}

// Used by: Admin Dashboard (Global Orders with Filter)
func (q *Queries) ListOrdersAdmin(ctx context.Context, arg ListOrdersAdminParams) ([]ListOrdersAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersAdmin, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersAdminRow
	for rows.Next() {
		var i ListOrdersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.FinalPrice,
			&i.OrderStatus,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UserName,
			&i.VendorName,
			&i.PickupAddress,
			&i.ServicesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT
    o.id,
    o.request_id,
    o.final_price,
    o.order_status,
    o.payment_status,
    o.created_at,

    v.display_name AS vendor_name,
    v.phone        AS vendor_phone,

    r.pickup_address,

    COALESCE(s.services_json, '[]'::jsonb) AS services_json

FROM orders o

         JOIN users v
              ON v.id = o.vendor_id

         JOIN requests r
              ON r.id = o.request_id

         LEFT JOIN LATERAL (
    SELECT jsonb_agg(
                   jsonb_build_object(
                           'category_id', c.id,
                           'category_name', c.name,
                           'selected_unit', rs.selected_unit,
                           'quantity_value', rs.quantity_value
                   )
           ) AS services_json
    FROM request_services rs
             JOIN categories c ON c.id = rs.category_id
    WHERE rs.request_id = o.request_id
    ) s ON true

WHERE o.user_id = $1

ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ListOrdersByUserRow struct {
	ID            uuid.UUID
	RequestID     uuid.UUID
	FinalPrice    string
	OrderStatus   OrderStatus
	PaymentStatus PaymentStatus
	CreatedAt     time.Time
	VendorName    string
	VendorPhone   string
	PickupAddress string
	ServicesJson  []byte
}

// Used by: User / Vendor / Admin (Order Detail Page)
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserRow
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.FinalPrice,
			&i.OrderStatus,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.VendorName,
			&i.VendorPhone,
			&i.PickupAddress,
			&i.ServicesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByVendor = `-- name: ListOrdersByVendor :many
SELECT
    o.id,
    o.request_id,
    o.final_price,
    o.order_status,
    o.payment_status,
    o.pickup_time,
    o.created_at,

    u.display_name AS user_name,
    u.phone        AS user_phone,

    r.pickup_address,
    r.pickup_time_from,
    r.pickup_time_to,

    COALESCE(s.services_json, '[]'::jsonb) AS services_json

FROM orders o

         JOIN users u
              ON u.id = o.user_id

         JOIN requests r
              ON r.id = o.request_id

         LEFT JOIN LATERAL (
    SELECT jsonb_agg(
                   jsonb_build_object(
                           'category_id', c.id,
                           'category_name', c.name,
                           'selected_unit', rs.selected_unit,
                           'quantity_value', rs.quantity_value
                   )
           ) AS services_json
    FROM request_services rs
             JOIN categories c ON c.id = rs.category_id
    WHERE rs.request_id = o.request_id
    ) s ON true

WHERE o.vendor_id = $1
  AND (
    $4::order_status IS NULL
        OR o.order_status = $4::order_status
    )

ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByVendorParams struct {
	VendorID uuid.UUID
	Limit    int32
	Offset   int32
	Status   NullOrderStatus
}

type ListOrdersByVendorRow struct {
	ID             uuid.UUID
	RequestID      uuid.UUID
	FinalPrice     string
	OrderStatus    OrderStatus
	PaymentStatus  PaymentStatus
	PickupTime     sql.NullTime
	CreatedAt      time.Time
	UserName       string
	UserPhone      string
	PickupAddress  string
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	ServicesJson   []byte
}

func (q *Queries) ListOrdersByVendor(ctx context.Context, arg ListOrdersByVendorParams) ([]ListOrdersByVendorRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByVendor,
		arg.VendorID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByVendorRow
	for rows.Next() {
		var i ListOrdersByVendorRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.FinalPrice,
			&i.OrderStatus,
			&i.PaymentStatus,
			&i.PickupTime,
			&i.CreatedAt,
			&i.UserName,
			&i.UserPhone,
			&i.PickupAddress,
			&i.PickupTimeFrom,
			&i.PickupTimeTo,
			&i.ServicesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE orders
SET payment_status = 'PAID',
    updated_at = now()
WHERE id = $1
  AND payment_status = 'UNPAID'
`

// Used by: Payment Service (Mark Paid)
func (q *Queries) MarkOrderPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOrderPaid, id)
	return err
}

const markOrderRefunded = `-- name: MarkOrderRefunded :exec
UPDATE orders
SET payment_status = 'REFUNDED',
    updated_at = now()
WHERE id = $1
  AND payment_status = 'PAID'
`

// Used by: Payment Service (Refund)
func (q *Queries) MarkOrderRefunded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOrderRefunded, id)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET order_status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID          uuid.UUID
	OrderStatus OrderStatus
}

// Used by: Vendor (Status Progression)
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.ID, arg.OrderStatus)
	return err
}
