// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    payer_id,
    vendor_id,
    amount,
    payment_method,
    payment_status,
    gateway_reference
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID          uuid.UUID
	PayerID          uuid.UUID
	VendorID         uuid.UUID
	Amount           string
	PaymentMethod    PaymentMethodType
	PaymentStatus    PaymentStatus
	GatewayReference sql.NullString
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.PayerID,
		arg.VendorID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.GatewayReference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.GatewayReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByGatewayReference = `-- name: GetPaymentByGatewayReference :one
SELECT id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at FROM payments WHERE gateway_reference = $1 LIMIT 1
`

func (q *Queries) GetPaymentByGatewayReference(ctx context.Context, gatewayReference sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByGatewayReference, gatewayReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.GatewayReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at FROM payments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.GatewayReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at FROM payments WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.GatewayReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at FROM payments
WHERE payer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByUserParams struct {
	PayerID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByUser, arg.PayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PayerID,
			&i.VendorID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.GatewayReference,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE orders
SET payment_status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, offer_id, user_id, vendor_id, final_price, order_status, payment_status, pickup_time, delivery_time, created_at, updated_at
`

type UpdateOrderPaymentStatusParams struct {
	ID            uuid.UUID
	PaymentStatus PaymentStatus
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OfferID,
		&i.UserID,
		&i.VendorID,
		&i.FinalPrice,
		&i.OrderStatus,
		&i.PaymentStatus,
		&i.PickupTime,
		&i.DeliveryTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET payment_status = $2,
    gateway_reference = COALESCE($3, gateway_reference),
    paid_at = CASE WHEN $2 = 'PAID'::payment_status AND paid_at IS NULL THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, payer_id, vendor_id, amount, payment_method, payment_status, gateway_reference, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID               uuid.UUID
	PaymentStatus    PaymentStatus
	GatewayReference sql.NullString
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.PaymentStatus, arg.GatewayReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.GatewayReference,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
