// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_settings.sql

package db

import (
	"context"
)

const getPlatformSettings = `-- name: GetPlatformSettings :one
SELECT id, commission_percentage, updated_at FROM platform_settings WHERE id = 1 LIMIT 1
`

func (q *Queries) GetPlatformSettings(ctx context.Context) (PlatformSetting, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSettings)
	var i PlatformSetting
	err := row.Scan(&i.ID, &i.CommissionPercentage, &i.UpdatedAt)
	return i, err
}

const updateCommissionPercentage = `-- name: UpdateCommissionPercentage :one
UPDATE platform_settings
SET commission_percentage = $1,
    updated_at = now()
WHERE id = 1
RETURNING id, commission_percentage, updated_at
`

func (q *Queries) UpdateCommissionPercentage(ctx context.Context, commissionPercentage string) (PlatformSetting, error) {
	row := q.db.QueryRowContext(ctx, updateCommissionPercentage, commissionPercentage)
	var i PlatformSetting
	err := row.Scan(&i.ID, &i.CommissionPercentage, &i.UpdatedAt)
	return i, err
}
