// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getVendorRatingSummary = `-- name: GetVendorRatingSummary :one
SELECT
    COUNT(*)::bigint AS total_ratings,
    COALESCE(ROUND(AVG(rating)::numeric, 2), 0)::text AS average_rating
FROM ratings
WHERE vendor_id = $1
`

type GetVendorRatingSummaryRow struct {
	TotalRatings  int64
	AverageRating string
}

// Vendor average rating summary
func (q *Queries) GetVendorRatingSummary(ctx context.Context, vendorID uuid.UUID) (GetVendorRatingSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getVendorRatingSummary, vendorID)
	var i GetVendorRatingSummaryRow
	err := row.Scan(&i.TotalRatings, &i.AverageRating)
	return i, err
}

const listTopRatedVendors = `-- name: ListTopRatedVendors :many
SELECT
    r.vendor_id,
    u.display_name AS vendor_name,
    COUNT(*)::bigint AS total_ratings,
    COALESCE(ROUND(AVG(r.rating)::numeric, 2), 0)::text AS average_rating
FROM ratings r
JOIN users u ON u.id = r.vendor_id
GROUP BY r.vendor_id, u.display_name
ORDER BY AVG(r.rating) DESC, COUNT(*) DESC
LIMIT $1 OFFSET $2
`

type ListTopRatedVendorsParams struct {
	Limit  int32
	Offset int32
}

type ListTopRatedVendorsRow struct {
	VendorID      uuid.UUID
	VendorName    string
	TotalRatings  int64
	AverageRating string
}

// Admin top rated vendors
func (q *Queries) ListTopRatedVendors(ctx context.Context, arg ListTopRatedVendorsParams) ([]ListTopRatedVendorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopRatedVendors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopRatedVendorsRow
	for rows.Next() {
		var i ListTopRatedVendorsRow
		if err := rows.Scan(
			&i.VendorID,
			&i.VendorName,
			&i.TotalRatings,
			&i.AverageRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorRatings = `-- name: ListVendorRatings :many
SELECT
    r.id,
    r.order_id,
    r.user_id,
    u.display_name AS user_name,
    r.rating,
    r.review,
    r.created_at
FROM ratings r
JOIN users u ON u.id = r.user_id
WHERE r.vendor_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListVendorRatingsParams struct {
	VendorID uuid.UUID
	Limit    int32
	Offset   int32
}

type ListVendorRatingsRow struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	UserID    uuid.UUID
	UserName  string
	Rating    int16
	Review    sql.NullString
	CreatedAt time.Time
}

// Vendor dashboard ratings list
func (q *Queries) ListVendorRatings(ctx context.Context, arg ListVendorRatingsParams) ([]ListVendorRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVendorRatings, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorRatingsRow
	for rows.Next() {
		var i ListVendorRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.UserName,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrderRating = `-- name: UpsertOrderRating :one
INSERT INTO ratings (
    order_id,
    user_id,
    vendor_id,
    rating,
    review
)
SELECT
    o.id,
    o.user_id,
    o.vendor_id,
    $1,
    NULLIF(trim($2), '')
FROM orders o
WHERE o.id = $3
  AND o.user_id = $4
  AND o.order_status IN ('DELIVERING', 'COMPLETED')
ON CONFLICT (order_id)
DO UPDATE
SET rating = EXCLUDED.rating,
    review = EXCLUDED.review,
    updated_at = now()
RETURNING id, order_id, user_id, vendor_id, rating, review, created_at, updated_at
`

type UpsertOrderRatingParams struct {
	Rating  int16
	Review  string
	OrderID uuid.UUID
	UserID  uuid.UUID
}

// User can add/update rating for completed or delivering order
func (q *Queries) UpsertOrderRating(ctx context.Context, arg UpsertOrderRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, upsertOrderRating,
		arg.Rating,
		arg.Review,
		arg.OrderID,
		arg.UserID,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.VendorID,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
