// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addRequestService = `-- name: AddRequestService :one
INSERT INTO request_services (
    request_id,
    category_id,
    selected_unit,
    quantity_value,
    items_json,
    description
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, request_id, category_id, selected_unit, quantity_value, items_json, description, created_at
`

type AddRequestServiceParams struct {
	RequestID     uuid.UUID
	CategoryID    uuid.UUID
	SelectedUnit  PricingUnit
	QuantityValue float64
	ItemsJson     pqtype.NullRawMessage
	Description   sql.NullString
}

// Used immediately after CreateRequest
func (q *Queries) AddRequestService(ctx context.Context, arg AddRequestServiceParams) (RequestService, error) {
	row := q.db.QueryRowContext(ctx, addRequestService,
		arg.RequestID,
		arg.CategoryID,
		arg.SelectedUnit,
		arg.QuantityValue,
		arg.ItemsJson,
		arg.Description,
	)
	var i RequestService
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CategoryID,
		&i.SelectedUnit,
		&i.QuantityValue,
		&i.ItemsJson,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const cancelRequest = `-- name: CancelRequest :exec
UPDATE requests
SET status = 'CANCELLED',
    updated_at = now()
WHERE id = $1
  AND status = 'OPEN'
`

// Used by: User
func (q *Queries) CancelRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelRequest, id)
	return err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    user_id,
    pickup_address,
    pickup_lat,
    pickup_lng,
    pickup_time_from,
    pickup_time_to,
    payment_method,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, pickup_address, pickup_time_from, pickup_time_to, payment_method, status, expires_at, created_at, updated_at, pickup_lat, pickup_lng
`

type CreateRequestParams struct {
	UserID         uuid.UUID
	PickupAddress  string
	PickupLat      sql.NullFloat64
	PickupLng      sql.NullFloat64
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	PaymentMethod  PaymentMethod
	ExpiresAt      sql.NullTime
}

// Used by: User
func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.UserID,
		arg.PickupAddress,
		arg.PickupLat,
		arg.PickupLng,
		arg.PickupTimeFrom,
		arg.PickupTimeTo,
		arg.PaymentMethod,
		arg.ExpiresAt,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PickupAddress,
		&i.PickupTimeFrom,
		&i.PickupTimeTo,
		&i.PaymentMethod,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PickupLat,
		&i.PickupLng,
	)
	return i, err
}

const expireRequests = `-- name: ExpireRequests :exec
UPDATE requests
SET status = 'EXPIRED',
    updated_at = now()
WHERE status = 'OPEN'
  AND expires_at IS NOT NULL
  AND expires_at <= now()
`

// Not exposed as public API
func (q *Queries) ExpireRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireRequests)
	return err
}

const getRequestStatsFiltered = `-- name: GetRequestStatsFiltered :one
SELECT
    COUNT(*) AS total_requests,

    COUNT(*) FILTER (WHERE status = 'OPEN')          AS open_requests,
    COUNT(*) FILTER (WHERE status = 'EXPIRED')       AS expired_requests,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')     AS cancelled_requests,
    COUNT(*) FILTER (WHERE status = 'ORDER_CREATED') AS order_created_requests

FROM requests
WHERE
    (
        $1::uuid IS NULL
            OR user_id = $1::uuid
    )
`

type GetRequestStatsFilteredRow struct {
	TotalRequests        int64
	OpenRequests         int64
	ExpiredRequests      int64
	CancelledRequests    int64
	OrderCreatedRequests int64
}

// Used by: Admin Dashboard
func (q *Queries) GetRequestStatsFiltered(ctx context.Context, userID uuid.NullUUID) (GetRequestStatsFilteredRow, error) {
	row := q.db.QueryRowContext(ctx, getRequestStatsFiltered, userID)
	var i GetRequestStatsFilteredRow
	err := row.Scan(
		&i.TotalRequests,
		&i.OpenRequests,
		&i.ExpiredRequests,
		&i.CancelledRequests,
		&i.OrderCreatedRequests,
	)
	return i, err
}

const getRequestWithServices = `-- name: GetRequestWithServices :many
SELECT
    r.id, r.user_id, r.pickup_address, r.pickup_time_from, r.pickup_time_to, r.payment_method, r.status, r.expires_at, r.created_at, r.updated_at, r.pickup_lat, r.pickup_lng,
    rs.id AS service_id,
    rs.category_id,
    c.name AS category_name,
    rs.selected_unit,
    rs.quantity_value,
    rs.items_json,
    rs.description
FROM requests r
         LEFT JOIN request_services rs ON rs.request_id = r.id
         LEFT JOIN categories c ON c.id = rs.category_id
WHERE r.id = $1
`

type GetRequestWithServicesRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PickupAddress  string
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	PaymentMethod  PaymentMethod
	Status         RequestsStatus
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PickupLat      sql.NullFloat64
	PickupLng      sql.NullFloat64
	ServiceID      uuid.NullUUID
	CategoryID     uuid.NullUUID
	CategoryName   sql.NullString
	SelectedUnit   NullPricingUnit
	QuantityValue  sql.NullFloat64
	ItemsJson      pqtype.NullRawMessage
	Description    sql.NullString
}

// Used by Vendor, Admin, and User
func (q *Queries) GetRequestWithServices(ctx context.Context, id uuid.UUID) ([]GetRequestWithServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRequestWithServices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequestWithServicesRow
	for rows.Next() {
		var i GetRequestWithServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PickupAddress,
			&i.PickupTimeFrom,
			&i.PickupTimeTo,
			&i.PaymentMethod,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PickupLat,
			&i.PickupLng,
			&i.ServiceID,
			&i.CategoryID,
			&i.CategoryName,
			&i.SelectedUnit,
			&i.QuantityValue,
			&i.ItemsJson,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketplaceRequests = `-- name: ListMarketplaceRequests :many
SELECT
    r.id,
    r.pickup_address,
    r.pickup_lat,
    r.pickup_lng,
    r.pickup_time_from,
    r.pickup_time_to,
    r.expires_at,
    r.created_at,
    CASE
        WHEN $3::double precision IS NULL
            OR $4::double precision IS NULL
            OR r.pickup_lat IS NULL
            OR r.pickup_lng IS NULL
            THEN NULL
        ELSE (
            6371 * acos(
                least(
                    1,
                    cos(radians($3::double precision)) *
                    cos(radians(r.pickup_lat)) *
                    cos(radians(r.pickup_lng) - radians($4::double precision)) +
                    sin(radians($3::double precision)) *
                    sin(radians(r.pickup_lat))
                )
            )
        )
    END AS distance_km,

    COUNT(rs.id) AS service_count,
    COALESCE(SUM(rs.quantity_value), 0)::double precision AS total_quantity,

    COALESCE(
                    jsonb_agg(
                    jsonb_build_object(
                            'category_id', rs.category_id,
                            'category_name', c.name,
                            'selected_unit', rs.selected_unit,
                            'quantity_value', rs.quantity_value
                    )
                            ) FILTER (WHERE rs.id IS NOT NULL),
                    '[]'::jsonb
    )::jsonb AS services_json

FROM requests r
         LEFT JOIN request_services rs ON rs.request_id = r.id
         LEFT JOIN categories c ON c.id = rs.category_id

WHERE r.status = 'OPEN'
  AND r.expires_at > now()
  AND (
    $5::uuid IS NULL
        OR rs.category_id = $5::uuid
    )
  AND (
    $6::double precision IS NULL
        OR (
            r.pickup_lat IS NOT NULL
            AND r.pickup_lng IS NOT NULL
            AND $3::double precision IS NOT NULL
            AND $4::double precision IS NOT NULL
            AND (
                6371 * acos(
                    least(
                        1,
                        cos(radians($3::double precision)) *
                        cos(radians(r.pickup_lat)) *
                        cos(radians(r.pickup_lng) - radians($4::double precision)) +
                        sin(radians($3::double precision)) *
                        sin(radians(r.pickup_lat))
                    )
                )
            ) <= $6::double precision
        )
    )

GROUP BY r.id
ORDER BY
    CASE
        WHEN $7 = 'nearest'
            THEN
                CASE
                    WHEN $3::double precision IS NULL
                        OR $4::double precision IS NULL
                        OR r.pickup_lat IS NULL
                        OR r.pickup_lng IS NULL
                        THEN 1000000000
                    ELSE (
                        6371 * acos(
                            least(
                                1,
                                cos(radians($3::double precision)) *
                                cos(radians(r.pickup_lat)) *
                                cos(radians(r.pickup_lng) - radians($4::double precision)) +
                                sin(radians($3::double precision)) *
                                sin(radians(r.pickup_lat))
                            )
                        )
                    )
                END
        END ASC,
    CASE
        WHEN $7 = 'expiring'
            THEN r.expires_at
        END ASC,
    r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMarketplaceRequestsParams struct {
	Limit         int32
	Offset        int32
	VendorLat     sql.NullFloat64
	VendorLng     sql.NullFloat64
	CategoryID    uuid.NullUUID
	MaxDistanceKm sql.NullFloat64
	SortBy        interface{}
}

type ListMarketplaceRequestsRow struct {
	ID             uuid.UUID
	PickupAddress  string
	PickupLat      sql.NullFloat64
	PickupLng      sql.NullFloat64
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
	DistanceKm     interface{}
	ServiceCount   int64
	TotalQuantity  float64
	ServicesJson   []byte
}

// Used by Vendor Dashboard
func (q *Queries) ListMarketplaceRequests(ctx context.Context, arg ListMarketplaceRequestsParams) ([]ListMarketplaceRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketplaceRequests,
		arg.Limit,
		arg.Offset,
		arg.VendorLat,
		arg.VendorLng,
		arg.CategoryID,
		arg.MaxDistanceKm,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketplaceRequestsRow
	for rows.Next() {
		var i ListMarketplaceRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PickupAddress,
			&i.PickupLat,
			&i.PickupLng,
			&i.PickupTimeFrom,
			&i.PickupTimeTo,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DistanceKm,
			&i.ServiceCount,
			&i.TotalQuantity,
			&i.ServicesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsAdmin = `-- name: ListRequestsAdmin :many
SELECT id, user_id, pickup_address, pickup_lat, pickup_lng, pickup_time_from, pickup_time_to,
       payment_method, status, expires_at, created_at, updated_at
FROM requests
WHERE (
          $3::requests_status IS NULL
              OR status = $3::requests_status
          )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRequestsAdminParams struct {
	Limit  int32
	Offset int32
	Status NullRequestsStatus
}

type ListRequestsAdminRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PickupAddress  string
	PickupLat      sql.NullFloat64
	PickupLng      sql.NullFloat64
	PickupTimeFrom time.Time
	PickupTimeTo   time.Time
	PaymentMethod  PaymentMethod
	Status         RequestsStatus
	ExpiresAt      sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Used by: Admin Panel
func (q *Queries) ListRequestsAdmin(ctx context.Context, arg ListRequestsAdminParams) ([]ListRequestsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsAdmin, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsAdminRow
	for rows.Next() {
		var i ListRequestsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PickupAddress,
			&i.PickupLat,
			&i.PickupLng,
			&i.PickupTimeFrom,
			&i.PickupTimeTo,
			&i.PaymentMethod,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRequests = `-- name: ListUserRequests :many
SELECT id, user_id, pickup_address, pickup_time_from, pickup_time_to, payment_method, status, expires_at, created_at, updated_at, pickup_lat, pickup_lng
FROM requests
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserRequestsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

// Used by: User Dashboard
func (q *Queries) ListUserRequests(ctx context.Context, arg ListUserRequestsParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listUserRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PickupAddress,
			&i.PickupTimeFrom,
			&i.PickupTimeTo,
			&i.PaymentMethod,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PickupLat,
			&i.PickupLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestOrderCreated = `-- name: SetRequestOrderCreated :exec
UPDATE requests
SET status = 'ORDER_CREATED',
    updated_at = now()
WHERE id = $1
  AND status = 'OPEN'
`

// Prevents further bidding
func (q *Queries) SetRequestOrderCreated(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setRequestOrderCreated, id)
	return err
}
