// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlements.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVendorSettlement = `-- name: CreateVendorSettlement :one
INSERT INTO vendor_settlements (
    vendor_id,
    amount,
    payment_method,
    reference
) VALUES (
    $1, $2, $3, $4
) RETURNING id, vendor_id, amount, payment_method, reference, status, paid_at, created_at, updated_at
`

type CreateVendorSettlementParams struct {
	VendorID      uuid.UUID
	Amount        string
	PaymentMethod PaymentMethodType
	Reference     sql.NullString
}

func (q *Queries) CreateVendorSettlement(ctx context.Context, arg CreateVendorSettlementParams) (VendorSettlement, error) {
	row := q.db.QueryRowContext(ctx, createVendorSettlement,
		arg.VendorID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Reference,
	)
	var i VendorSettlement
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Reference,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorSettlementByID = `-- name: GetVendorSettlementByID :one
SELECT id, vendor_id, amount, payment_method, reference, status, paid_at, created_at, updated_at FROM vendor_settlements WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVendorSettlementByID(ctx context.Context, id uuid.UUID) (VendorSettlement, error) {
	row := q.db.QueryRowContext(ctx, getVendorSettlementByID, id)
	var i VendorSettlement
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Reference,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendorSettlements = `-- name: ListVendorSettlements :many
SELECT id, vendor_id, amount, payment_method, reference, status, paid_at, created_at, updated_at FROM vendor_settlements
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVendorSettlementsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVendorSettlements(ctx context.Context, arg ListVendorSettlementsParams) ([]VendorSettlement, error) {
	rows, err := q.db.QueryContext(ctx, listVendorSettlements, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorSettlement
	for rows.Next() {
		var i VendorSettlement
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Amount,
			&i.PaymentMethod,
			&i.Reference,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorSettlementsByVendor = `-- name: ListVendorSettlementsByVendor :many
SELECT id, vendor_id, amount, payment_method, reference, status, paid_at, created_at, updated_at FROM vendor_settlements
WHERE vendor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVendorSettlementsByVendorParams struct {
	VendorID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListVendorSettlementsByVendor(ctx context.Context, arg ListVendorSettlementsByVendorParams) ([]VendorSettlement, error) {
	rows, err := q.db.QueryContext(ctx, listVendorSettlementsByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorSettlement
	for rows.Next() {
		var i VendorSettlement
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Amount,
			&i.PaymentMethod,
			&i.Reference,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorSettlementStatus = `-- name: UpdateVendorSettlementStatus :one
UPDATE vendor_settlements
SET status = $2,
    paid_at = CASE WHEN $2 = 'VERIFIED'::settlement_status AND paid_at IS NULL THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, vendor_id, amount, payment_method, reference, status, paid_at, created_at, updated_at
`

type UpdateVendorSettlementStatusParams struct {
	ID     uuid.UUID
	Status SettlementStatus
}

func (q *Queries) UpdateVendorSettlementStatus(ctx context.Context, arg UpdateVendorSettlementStatusParams) (VendorSettlement, error) {
	row := q.db.QueryRowContext(ctx, updateVendorSettlementStatus, arg.ID, arg.Status)
	var i VendorSettlement
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Reference,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
